export const KELAS_LIST_REQUEST = 'KELAS_LIST_REQUEST'
export const KELAS_LIST_SUCCESS = 'KELAS_LIST_SUCCESS'
export const KELAS_LIST_FAIL = 'KELAS_LIST_FAIL'

export const KELAS_DETAIL_REQUEST = 'KELAS_DETAIL_REQUEST'
export const KELAS_DETAIL_SUCCESS = 'KELAS_DETAIL_SUCCESS'
export const KELAS_DETAIL_FAIL = 'KELAS_DETAIL_FAIL'

export const ARTIKEL_LIST_REQUEST = 'ARTIKEL_LIST_REQUEST'
export const ARTIKEL_LIST_SUCCESS = 'ARTIKEL_LIST_SUCCESS'
export const ARTIKEL_LIST_FAIL = 'ARTIKEL_LIST_FAIL'
