export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_KELAS_FAIL = 'USER_KELAS_FAIL';
export const USER_KELAS_REQUEST = 'USER_KELAS_REQUEST';
export const USER_KELAS_SUCCESS = 'USER_KELAS_SUCCESS';

export const USER_KELAS_DETAIL_REQUEST = 'USER_KELAS_DETAIL_REQUEST';
export const USER_KELAS_DETAIL_SUCCESS = 'USER_KELAS_DETAIL_SUCCESS';
export const USER_KELAS_DETAIL_FAIL = 'USER_KELAS_DETAIL_FAIL';

export const USER_ARTIKEL_FAIL = 'USER_ARTIKEL_FAIL';
export const USER_ARTIKEL_REQUEST = 'USER_ARTIKEL_REQUEST';
export const USER_ARTIKEL_SUCCESS = 'USER_ARTIKEL_SUCCESS';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_STATUS_RESET = 'USER_REGISTER_STATUS_RESET';
